### PR TITLE
line-height in titles

### PR DESCRIPTION
**Pull request by mansona**
This is just re-opening #219 so that Percy can build it with our token 👍 

I'm happy to merge if percy passes 🎉

### CODE REVIEW

**Comment by locks** [comment]
Narrator: Percy didn't pass.

**Comment by mansona** [comment]
@betocantu93 I'm looking at the Percy output and it seems to be adding a lot of unnecessary padding to cases where the code samples are not going onto the next line 🤔 

image 2018-10-04 at 9 43 41 a m

Was this intentional?

**Comment by betocantu93** [comment]
Hello, no, it wasn't... Maybe I can try other approach

**Comment by mansona** [comment]
@betocantu93 cool! I think you can keep pushing to your own fork/branch and if you let me know I will fetch/push it here so that we can compare the percy output 👍

**Comment by betocantu93** [comment]
Aight, I'll let you know, thanks.

**Comment by mansona** [comment]
@betocantu93 it looks like this has already been solved in the ember-styleguide 🤔 https://github.com/ember-learn/ember-styleguide/issues/94 it makes me wonder if the problem is that we're just not using any of the styleguide styles here or if they are being overridden somehow 🤔 

Maybe you could check against master of the styleguide and if it's fixed then we can focus on getting a styleguide version cut 👍

**Comment by mansona** [comment]
It looks like this has been fixed by updating the ember-styleguide 👍

**Pull request closed without merging**
