### PR TITLE
Remove and enforce no jquery

### PR DESCRIPTION
**Pull request by rwwagner90**
Apparently, ember-percy uses jQuery, so had to remove it. Not sure how people feel about that. Got the rest working without jQuery, but have one failing test. Does anyone have any ideas why the test is failing?

### CODE REVIEW

**Comment by rwwagner90** [comment]
Hmm, looks like I broke fastboot at some point as well

**Comment by rwwagner90** [comment]
Looks like fetch does not like `/content/foo.json` since it's a relative path. Anyone know the absolute paths and/or how to fix this?

**Comment by mansona** [comment]
👋 thanks for the PR

I've added this to the "Post-Release Phase" project because it's unlikely that we're going to merge this ahead of the first release. I will look into the issues you raised after that initial release 👍

**Comment by mansona** [comment]
Also, I just had another thought 🤔 

On a more fundamental level... is there really a point in doing this whole change if Prism requires jQuery? Did you run this locally and was jQuery actually removed from the output vendor? 

This whole thing needs more discussion at a learning team meeting before we can proceed.

**Comment by acorncom** [comment]
@mansona although this PR might feel a bit it the blue, for context, Robert has been updating various apps the learn team runs to remove jQuery this week. The goal here is to dog food the approach, find snags early prior to it being common and help pave the path for the community. Because although not having jQuery in your app isn’t ever going to be *required*, it’s the type of thing that would be nice to first allow (and down the road might become the new default blueprint at some point in the future). Plus, we’ll want to point folks interested in doing this type of change toward learn team apps ... 

Re your prism JS question, unless I’m missing something on their website it doesn’t look like jQuery is used at all?

@rwwagner90 thanks for doing this. We’ve specifically been using `ember-percy` on this app in the interests of ensuring a smooth transition to the new guides app, so seems better to not remove it. In the interests of paving the way for the community, would you be able to work with the Percy folks on seeing what it would take to remove jQuery in their addon (and if they’d be up for it)? Happy to help with introductions there if needed ...

**Comment by rwwagner90** [comment]
@mansona there is definitely a point in striving for no jQuery. Even if something else happens to be pulling it in, this removes it from the things within our immediate control. Just need to figure out why the one test is failing, if you wouldn't mind helping out there 😃 .

@acorncom I can definitely work with them. There is an open PR to remove jQuery from ember-percy that I commented on yesterday. We'll get that done and add it back before we merge this.

**Comment by mansona** [comment]
@acorncom Thank you for the context, I understand the drive of doing this now and I accept the reasons to do so 👍 

I have a few specific questions: 

Do we have these reasons documented anywhere? as a Markdown on a repo or anything? The reason I ask is that #37 description is a little bit invalid in this context, instead of saying "to remove bloat" we should literally quote **you** saying: 

> The goal here is to dog food the approach, find snags early prior to it being common and help pave the path for the community. Because although not having jQuery in your app isn’t ever going to be required, it’s the type of thing that would be nice to first allow (and down the road might become the new default blueprint at some point in the future). Plus, we’ll want to point folks interested in doing this type of change toward learn team apps ...

I would prefer to reference a central markdown but, in the interest of expediency I have already updated the issue to quote you 👍 

My second question: are you happy with my assertion that this **should not be merged before first release**? I am very wary of putting something in between now and a release that could end up being a blocker, and again now that I understand the context a bit more I'm happy to do this _very_ soon after the initial release.

**Comment by acorncom** [comment]
@masona yes, let’s not have this block the initial release :+1: Shipping first and improvements later 🙂

**Comment by acorncom** [comment]
One other thing here that crossed my mind this morning. If/when we remove jQuery, we'll also need to make sure the removal doesn't break our current Algolia search scraping setup. Algolia currently uses the code referenced here (https://github.com/algolia/docsearch-configs/blob/master/configs/emberjs_versions.json#L7-L10) to scrape our dropdown select and pull the versions we want to scrape. We'll need to adjust that as applicable. I'll cross-post this to the issue as well ...

**Comment by sivakumar-kailasam** [comment]
Sorry @rwwagner90 its been a while & looks like we need a bit of work to get this up-to-date, so closing this for now. Please feel free to reopen this with all the comments considered.

**Comment by rwwagner90** [comment]
@sivakumar-kailasam no worries! I was waiting for percy to work without jQuery, which it does now, and we can start down this path again. I'm hoping to get back in the groove working on OSS soon, but have needed 100% of my time for client work recently.

**Comment by mansona** [comment]
@rwwagner90 let's have a chat about Prism too when you're back in the groove 😂

**Pull request closed without merging**
