### PR TITLE
Update guides-article.hbs

### PR DESCRIPTION
**Pull request by Yugaank-Kalia**

### CODE REVIEW

**Comment by Yugaank-Kalia** [comment]
Hey Chris,

The reason is probably because I put it inside another div I just need to change the css file of this. Can you tell me which file it would be, I'll be grateful.


Regards,

Yugaank Kalia

________________________________

**Comment by mansona** [comment]
@Yugaank-Kalia I don't know exactly what file to change but you can see the styles in the `app/styles` folder https://github.com/ember-learn/guides-app/tree/master/app/styles

Have you been able to run this app locally?

**Comment by Yugaank-Kalia** [comment]
I'll get back to you asap. I'll run it locally to check.


Regards,

Yugaank Kalia

________________________________

**Comment by mansona** [comment]
hey @Yugaank-Kalia 👋 

Thank you so much for your contribution. We have now fixed this issue in #278 👍 

Let me know if there is anything else you would like to help with and I am happy to answer any questions you might have. The current project that we're focusing on can be seen here: https://github.com/orgs/ember-learn/projects/10

**Pull request closed without merging**
