### PR TITLE
Updating the metadata system

### PR DESCRIPTION
**Pull request by mansona**
This gives us quite a few things out of the box. I have created a review app for this PR because a lot of it you will have to see in the compiled output to appreciate what's happening.

First major update: we're now using @rwwagner90's [ember-meta](https://github.com/shipshapecode/ember-meta) plugin. This has been a collaborative effort but essentially it works really nicely to remove a lot of the complexity required to get the metadata right. Special shout out to @sivakumar-kailasam too 🎉 

So this is what is now being added to the `<head>` as a result of this PR: 

```html

<meta name="ember-cli-head-start" content>

<!---->
<meta name="description" content="Welcome to the Ember.js Guides! This documentation will take you from total beginner to Ember expert. What is Ember? 

Ember is a JavaScript front-end framework designed to help you build websites with rich and complex user interactions. It does so by...">

<meta name="referrer" content="unsafe-url">

<link rel="canonical" href="https://guides.emberjs.com/release/">

<!---->
<!---->
<meta property="og:site_name" content="Ember">

<!---->
<meta property="og:url" content="https://guides.emberjs.com/release/">

<meta property="og:description" content="Welcome to the Ember.js Guides! This documentation will take you from total beginner to Ember expert. What is Ember? 

Ember is a JavaScript front-end framework designed to help you build websites with rich and complex user interactions. It does so by...">

<meta property="og:type" content="website">

<meta property="og:image" content="/images/logos/ember.png">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="256">
<meta property="og:image:height" content="256">

<meta name="twitter:card" content="summary">

<meta name="twitter:site" content="@emberjs">
<meta name="twitter:creator" content="@emberjs">

<meta name="twitter:image:src" content="/images/logos/ember.png">

<!---->
<meta name="twitter:url" content="https://guides.emberjs.com/release/">

<meta name="twitter:description" content="Welcome to the Ember.js Guides! This documentation will take you from total beginner to Ember expert. What is Ember? 

Ember is a JavaScript front-end framework designed to help you build websites with rich and complex user interactions. It does so by...">

<!---->
<!---->

<meta name="ember-cli-head-end" content>
```

This implementation takes the first 260 characters of the main content and uses that for the description but also allows for the optional overriding of the description with frontmatter in the markdown file.

You also have the ability to override the canonical link if the url on the `release` version has changed.

Here is what it looks like when you copy some links into slack now: 

screen shot 2018-06-01 at 12 22 07

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
Also description tag is repeated twice.

**Comment by mansona** [comment]
@sivakumar-kailasam what is the perceived benefit from `[removing] new lines in the description fields`?

**Comment by sivakumar-kailasam** [comment]
I originally said so because Google allows for 320chars in the description field and I didn't want to loose it to line breaks. But on second thought, if we're encountering a new line in the content, that's probably a good spot to mark as the end of the description to be trimmed. So that we're sure we've got at least one complete sentence in there.

**Comment by mansona** [comment]
@sivakumar-kailasam do you think we could look to get this PR merged (approved at least) and decide on the *improved* behaviour later? 

As it stands this greatly improves the situation and I wouldn't like the perfect to get in the way of the great 😂

**Comment by mansona** [comment]
also... what do you mean by "Google allows for 320 characters"? 🤔 

Doing a search for "Ember Component" is showing results that only have 160(ish) characters under the result:

screen shot 2018-06-01 at 17 04 52

@rwwagner90 maybe you can weigh in here? I was under the impression that this was just an Open Graph feature?

**Comment by sivakumar-kailasam** [comment]
ah may be i'm misinformed but I remembered it was to a max limit around 300 (https://moz.com/learn/seo/meta-description). 

In case you don't have the time to make that change now I'll go ahead & merge this.

**Comment by mansona** [comment]
@sivakumar-kailasam unfortunately if we needed to make that change it would required changes down the stack in ember-meta. 

So it's not *exactly* that I don't have the time but it means it would delay things a bit 😂 I'm also heading out for the evening soon so I'm short on time too 👍

**Comment by sivakumar-kailasam** [comment]
ah that's perfectly fine :) As long as its being tracked somewhere :)

**Comment by rwwagner90** [comment]
FWIW 300 is the "limit" for google and facebook, but they don't actually allow ones that long half the time.

**Pull request merged**
