### PR TITLE
user can choose code style for examples

### PR DESCRIPTION
**Pull request by BryanCrotaz**
**Preparation for official support of ES6 style**

Adds dropdown to choose example code style. Current choices are 'Ember Traditional' and 'ES6'.

In `guides-source`, label a code example with a style (`ember` or `es6`):

> Services must extend the [`Service`]> (https://www.emberjs.com/api/ember/release/modules/@ember%2Fservice) base class:
>
> \```javascript {data-filename=app/services/shopping-cart.js style=ember}
> import Service from '@ember/service';
>
> export default Service.extend({
> });
> \```
>
> \```javascript {data-filename=app/services/shopping-cart.js style=es6}
> import Service from '@ember/service';
>
> export default class ShoppingCart extends Service;
> \```

After rendering the MD any code examples tagged with the wrong style will be hidden. Any with no style tag will be displayed in order to be backwards compatible.

TODO: add warning to show that an example has not been provided in both forms.

This PR introduces an `options` service which can be used for other options later such as i18n language.

### CODE REVIEW

**Comment by mansona** [comment]
@BryanCrotaz could we get you to rebase this change? Now that we have Netlify installed we will even get a demo app so we can see what it looks like in a production-like environment on the PR 👍

**Comment by BryanCrotaz** [comment]
Looks like you need to increase the deploy timeout

**Comment by mansona** [comment]
@BryanCrotaz something strange seems to have gone on with this branch 🤔 it's telling me that there are 158 commits on your PR

Did you do a rebase or a merge to bring it up to date?

**Comment by mansona** [comment]
Also, it looks like the test is failing 🤔 maybe let's get this rebased first and then we can focus on fixing your new test? what do you think? Let me know if you need any assistance with anything 😄

**Comment by BryanCrotaz** [comment]
I rebased. I’ll create a new branch and cherry pick.

**Comment by mansona** [comment]
@BryanCrotaz I think I figured it out 🔍 

I **think** you may have merged your old branch after rebasing

screenshot 2018-11-02 at 10 34 22

I think if you reset to the commit just before that last merge and force push it should be ok 👍

**Comment by locks** [comment]
I think the problem that this approach is trying to solve is better addressed with a migration guide, instead of the overhead of having to sustain the duplication of every code sample.
We also want to make sure people fall in the pits of success as much as possible, and the happy path post-Octane edition will be the native `class` syntax.

Thank you for you contribution @BryanCrotaz! If you still have some time to contribute, drop by the learning channel so someone from the team can coordinate some work with you :)

**Pull request closed without merging**
