### PR TITLE
Use section-groups for Guides

### LINKED ISSUE #251: Fix the styles that are broken when using showdown-section-groups
We need to use showdown-section-groups to wrap each set of paragraphs between a Header tags in a <section>. This way we can create one index (possible search result) for each header in the content

### PR DESCRIPTION
**Pull request by mansona**
This is currently blocked by https://github.com/ember-learn/ember-styleguide/pull/102 and in all likelihood will be fixed once that is merged and released

Fixes #251

This PR is not complete, you will probably see that the Percy diffs are completely wrong 😖 If someone could continue where I left off and fix the styles so that we don't have crazy padding in a `<section>` that would be much appreciated 🎉

### CODE REVIEW

**Comment by beadams86** [comment]
> Fixes #251
> 
> This PR is not complete, you will probably see that the Percy diffs are completely wrong 😖 If someone could continue where I left off and fix the styles so that we don't have crazy padding in a `<section>` that would be much appreciated 🎉
I can fix the styling issue, taking a look now..

**Comment by beadams86** [comment]
EDIT: Actually the padding looks good to me...? Maybe this has already been fixed?

**Comment by mansona** [comment]
@beadams86 if you have a look at the Netlify deploy preview here: https://deploy-preview-252--ember-guides.netlify.com/release/ you will see the issue 😂 If you're running this locally you will need to fork from this branch `feature/section-groups` instead of master

**Comment by aklkv** [comment]
@mansona I think the way to fix padding is to remove global style definition from here  https://github.com/ember-learn/ember-styleguide/blob/master/addon/styles/addon.scss#L61

To me it feels a bit heavy handed to have this defended globally in a addon. It would be good idea to namespace it at list.

**Comment by mansona** [comment]
@aklkv thanks! yes you're right, removing most of the styles from that rule seems to have fixed it 👍 I've done the work over at the styleguide https://github.com/ember-learn/ember-styleguide/pull/102 and once that is released this should most likely be fixed

**Comment by mansona** [comment]
@sivakumar-kailasam that has been rebased now 👍

**Pull request merged**
